
import subprocess

get_api_url = "https://dev.refract-fosfor.com/registry/api/v1/model/export-model"

post_api_url = "https://dev.refract-fosfor.com/registry/api/v1/model/export-model"

auth_token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ4WTdTd3k5UE1xaXRDQmNSMm5qcVl6bmoxS3NqZzV3TmdOV0xDVzdyUkhvIn0.eyJleHAiOjE3MzAzNzE2OTEsImlhdCI6MTY5ODMxNzI5MSwiYXV0aF90aW1lIjoxNjk4MzExODc3LCJqdGkiOiI2ZTU0NTUzZC1lN2JjLTRhMTEtYmZkMi1hNzkwYWE2YzFkNDgiLCJpc3MiOiJodHRwczovL2Rldi1hdXRoLnJlZnJhY3QtZm9zZm9yLmNvbS9hdXRoL3JlYWxtcy9tb3NhaWMiLCJhdWQiOlsibW9zYWljLWdhdGVrZWVwZXIiLCJhY2NvdW50Il0sInN1YiI6IjM3ZTRkYTRjLTY2YTItNDIzMC1hMmY0LWIwYTg1NWE1YmExZSIsInR5cCI6IkJlYXJlciIsImF6cCI6Im1vc2FpYy1nYXRla2VlcGVyIiwic2Vzc2lvbl9zdGF0ZSI6IjEwYTBmMjcxLTc1MjEtNDExMC1iMDM4LWQyMjFiMTMzMjQ4MSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJsb25nX2xpdmVkX3Rva2VuIiwiTUxPUFMiLCJzcGVjdHJhLWRldmVsb3BlciIsInJlZnJhY3QtZGV2ZWxvcGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIiwicmVmcmFjdC1hZG1pbiIsInJlZnJhY3QtcmVhZG9ubHkiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBncm91cHMgdGVzdCBlbWFpbCB1c2VyX2F0dHJpYnV0ZSBwcm9maWxlIiwic2lkIjoiMTBhMGYyNzEtNzUyMS00MTEwLWIwMzgtZDIyMWIxMzMyNDgxIiwiYWF2ZXMiOlsibG9uZ19saXZlZF90b2tlbiIsIk1MT1BTIiwic3BlY3RyYS1kZXZlbG9wZXIiLCJyZWZyYWN0LWRldmVsb3BlciIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsInJlZnJhY3QtYWRtaW4iLCJyZWZyYWN0LXJlYWRvbmx5Il0sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidGVzdCI6WyJsb25nX2xpdmVkX3Rva2VuIiwiTUxPUFMiLCJzcGVjdHJhLWRldmVsb3BlciIsInJlZnJhY3QtZGV2ZWxvcGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIiwicmVmcmFjdC1hZG1pbiIsInJlZnJhY3QtcmVhZG9ubHkiXSwibmFtZSI6IlJlZnJhY3QgQWRtaW4iLCJncm91cHMiOlsibG9uZ19saXZlZF90b2tlbiIsIk1MT1BTIiwic3BlY3RyYS1kZXZlbG9wZXIiLCJyZWZyYWN0LWRldmVsb3BlciIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsInJlZnJhY3QtYWRtaW4iLCJyZWZyYWN0LXJlYWRvbmx5Il0sInByZWZlcnJlZF91c2VybmFtZSI6InJlZnJhY3QuYWRtaW4iLCJnaXZlbl9uYW1lIjoiUmVmcmFjdCIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6InJlZnJhY3QuYWRtaW5AZm9zZm9yLmNvbSJ9.iu-OXlVqdhfPBUDg3DUYaHiMDi2_WNOVm4_hIqSOh34ib2lzZiSQS9z8iOpPvtmPSGl46kFY7PQVvxKygnMzGxebrpMbHYFJiEuV_hYgaH_K_K1CD2dMRUD3fsKb4JgSJHGsEy7eLiv41cys36ZoDOD0PtGXGzsZTUcj3Aq_VGX2DKMeD5ET8wJtFWArBHl70zy49KdyjnUqnl7TdQLEMSxAG0UkH3Sseqq2MSDhEHzAoNd8syrQl85GAR7stravw_jigOKomJHw_a7NfpFPvk05Q-f1zxigpKh8Ud0ofE-ktz7lSruduaaRAs5ILJffK9qC0uahaiLfXru8EI1lOA"
get_command = f'curl -H "Authorization: Bearer {auth_token}" {get_api_url}'

get_response = subprocess.check_output(get_command, shell=True)


post_data = {

    "key1": "value1",

    "key2": "value2"

}

post_data_json = json.dumps(post_data)

post_command = f'curl -H "Authorization: Bearer {auth_token}" -H "Content-Type: application/json" -d \'{post_data_json}\' -X POST {https://dev.refract-fosfor.com/registry/api/v1/model/export-model}'
post_response = subprocess.check_output(post_command, shell=True)
